name: multiple_select
description: A versatile and beautiful multi-drop-down component for App developers.
version: 0.1.24
homepage: https://github.com/HunterVillage/multiple_select

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
